In [ ]:
# groupby

In [1]:
from pydoc import describe

import pandas as pd

In [2]:
data = {
    "Product": ["A","A","A","B","B","C"],
    "Category": ["Food","Food","Food","Drinks","Drinks", "Snacks"],
    "Sales": [10,15,7,20,22,5],
    "Store": ["X","Y","X","Y","X","Y"]
}

In [3]:
df = pd.DataFrame(data)
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [7]:
df.groupby("Product")["Sales"].sum()

Product
A    32
B    42
C     5
Name: Sales, dtype: int64

In [8]:
df.groupby("Product")["Sales"].mean()

Product
A    10.666667
B    21.000000
C     5.000000
Name: Sales, dtype: float64

In [9]:
df.groupby("Product")["Sales"].median()

Product
A    10.0
B    21.0
C     5.0
Name: Sales, dtype: float64

In [10]:
df.groupby("Store")["Sales"].sum()

Store
X    39
Y    40
Name: Sales, dtype: int64

In [18]:
df.groupby("Category")["Sales"].max().reset_index()

  Category  Sales
0   Drinks     22
1     Food     15
2   Snacks      5

In [17]:
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [19]:
df.groupby(["Product", "Store"])["Sales"].mean().reset_index()

  Product Store  Sales
0       A     X    8.5
1       A     Y   15.0
2       B     X   22.0
3       B     Y   20.0
4       C     Y    5.0

In [20]:
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [21]:
df.groupby("Category").agg({
    "Sales": ["sum","mean","count"]
})

         Sales
           sum       mean count
Category
Drinks      42  21.000000     2
Food        32  10.666667     3
Snacks       5   5.000000     1

In [22]:
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [23]:
df.pivot_table(
    values= "Sales", # what you want to summarize
    index = "Product", # this is the rows
    columns = "Store", # new columns created
    aggfunc= "sum" # calculation to apply inside each cell
)

Store       X     Y
Product
A        17.0  15.0
B        22.0  20.0
C         NaN   5.0

In [24]:
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [25]:
df.pivot_table(
    values= "Sales",
    index= "Category",
    columns= "Store",
    aggfunc= ["sum", "mean"]
)

           sum        mean
Store        X     Y     X     Y
Category
Drinks    22.0  20.0  22.0  20.0
Food      17.0  15.0   8.5  15.0
Snacks     NaN   5.0   NaN   5.0

In [26]:
pd.crosstab(df["Product"], df["Store"])

Store    X  Y
Product
A        2  1
B        1  1
C        0  1

In [27]:
pd.crosstab(df["Product"], df["Store"], margins=True)

Store    X  Y  All
Product
A        2  1    3
B        1  1    2
C        0  1    1
All      3  3    6

In [28]:
pd.crosstab(df["Product"], df["Store"], values= df["Sales"], aggfunc="sum")

Store       X     Y
Product
A        17.0  15.0
B        22.0  20.0
C         NaN   5.0

In [29]:
df

  Product Category  Sales Store
0       A     Food     10     X
1       A     Food     15     Y
2       A     Food      7     X
3       B   Drinks     20     Y
4       B   Drinks     22     X
5       C   Snacks      5     Y

In [30]:
df.describe()

           Sales
count   6.000000
mean   13.166667
std     6.968979
min     5.000000
25%     7.750000
50%    12.500000
75%    18.750000
max    22.000000

In [32]:
df["Sales"].sum()

np.int64(79)

In [33]:
df["Sales"].mean()

np.float64(13.166666666666666)

In [34]:
df["Sales"].min()

np.int64(5)

In [35]:
df["Sales"].max()

np.int64(22)

In [36]:
df["Sales"].median()

np.float64(12.5)

In [37]:
df.groupby("Category")["Sales"].describe()

          count       mean       std   min   25%   50%   75%   max
Category
Drinks      2.0  21.000000  1.414214  20.0  20.5  21.0  21.5  22.0
Food        3.0  10.666667  4.041452   7.0   8.5  10.0  12.5  15.0
Snacks      1.0   5.000000       NaN   5.0   5.0   5.0   5.0   5.0