In [1]:
import pandas as pd

In [4]:
data = {
    "color": ["red","blue","blue","green","red"],
    "size": ["S","M","L","M","L"]
}

In [5]:
df = pd.DataFrame(data)
df

   color size
0    red    S
1   blue    M
2   blue    L
3  green    M
4    red    L

In [6]:
pd.get_dummies(df,columns=["color", "size"])

   color_blue  color_green  color_red  size_L  size_M  size_S
0       False        False       True   False   False    True
1        True        False      False   False    True   False
2        True        False      False    True   False   False
3       False         True      False   False    True   False
4       False        False       True    True   False   False

In [8]:
animals = pd.DataFrame({"pet": ["dog","cat","dog","bird"]})
animals

    pet
0   dog
1   cat
2   dog
3  bird

In [9]:
pd.get_dummies(animals,columns=["pet"])

   pet_bird  pet_cat  pet_dog
0     False    False     True
1     False     True    False
2     False    False     True
3      True    False    False

In [10]:
#binning/discretization
# 0 to 100
# 0 to 17 child
# 18 to 64 adult
# 65+ senior

# poor, fair, good, excellent

In [11]:
ages = [15,22,37,45,72,16]

In [12]:
df = pd.DataFrame({"ages": ages})
df

   ages
0    15
1    22
2    37
3    45
4    72
5    16

In [13]:
bins = [0,18,65,120]

In [14]:
labels = ["child", "adult", "senior"]

In [16]:
df["group"] = pd.cut(df["ages"], bins=bins, labels=labels)
df

   ages   group
0    15   child
1    22   adult
2    37   adult
3    45   adult
4    72  senior
5    16   child

In [17]:
df = pd.DataFrame({"x": [1.2, 3.5, 5.8,9.1]})
df

     x
0  1.2
1  3.5
2  5.8
3  9.1

In [18]:
df["bin"] = pd.cut(df["x"], bins=3)
df

     x             bin
0  1.2  (1.192, 3.833]
1  3.5  (1.192, 3.833]
2  5.8  (3.833, 6.467]
3  9.1    (6.467, 9.1]

In [19]:
# Standard scaling (mean 0, std1)
# min max scaling (0 to 1)
# Age 0 -> 100
# Salary 0 -> 10000000

In [28]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [22]:
df = pd.DataFrame({"height": [150,160,165,170,180], "weight": [50,60,65,70,80]})
df

   height  weight
0     150      50
1     160      60
2     165      65
3     170      70
4     180      80

In [23]:
scaler = StandardScaler()
scaled = scaler.fit_transform(df)
scaled

array([[-1.5, -1.5],
       [-0.5, -0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 1.5,  1.5]])

In [24]:
df = pd.DataFrame({"x": [10,20,30]})
df

    x
0  10
1  20
2  30

In [29]:
scaler = MinMaxScaler()
scaler.fit_transform(df)

array([[0. ],
       [0.5],
       [1. ]])

In [30]:
# log sqrt

In [31]:
import numpy as np

In [32]:
df = pd.DataFrame({"income": [20000,30000,50000,90000]})
df

   income
0   20000
1   30000
2   50000
3   90000

In [33]:
df["log_income"] = np.log(df["income"])

In [34]:
df

   income  log_income
0   20000    9.903488
1   30000   10.308953
2   50000   10.819778
3   90000   11.407565

In [35]:
df = pd.DataFrame({"x": [1,4,9,16]})
df

    x
0   1
1   4
2   9
3  16

In [36]:
df["sqrt"] = np.sqrt(df["x"])

In [37]:
df

    x  sqrt
0   1   1.0
1   4   2.0
2   9   3.0
3  16   4.0

In [38]:
data = {
    "price": [100,200,150],
    "quantity": [2,3,4],
    "date": ["2024 01 01", "2024 01 02", "2024 01 03"]
}

In [39]:
df = pd.DataFrame(data)

In [40]:
df

   price  quantity        date
0    100         2  2024 01 01
1    200         3  2024 01 02
2    150         4  2024 01 03

In [41]:
df["total"] = df["price"] * df["quantity"]

In [42]:
df

   price  quantity        date  total
0    100         2  2024 01 01    200
1    200         3  2024 01 02    600
2    150         4  2024 01 03    600

In [43]:
df["date"] = pd.to_datetime(df["date"])

In [44]:
df["weekday"] = df["date"].dt.day_name()
df

   price  quantity       date  total    weekday
0    100         2 2024-01-01    200     Monday
1    200         3 2024-01-02    600    Tuesday
2    150         4 2024-01-03    600  Wednesday

In [45]:
df["unit_price"] = df["price"] / df["quantity"]

In [46]:
df

   price  quantity       date  total    weekday  unit_price
0    100         2 2024-01-01    200     Monday   50.000000
1    200         3 2024-01-02    600    Tuesday   66.666667
2    150         4 2024-01-03    600  Wednesday   37.500000