1. loc - select by label
2. iloc - for select by position
3. boolean masks - select rows that meet condition
4. conditional filtering - multiple rules (age > 20 and name == charlie)
5. multi-indexing - work with tables that have more than one index level

In [54]:
import pandas as pd
from jedi.inference.names import AbstractNameDefinition

In [55]:
data = {
    "date": ["01-01-2022", "01-01-2022", "02-01-2022", "03-01-2022", "03-01-2022"],
    "product": ["apple", "banana", "apple", "orange", "banana"],
    "price": [1.2, 0.8, 1.3, 1.5, 0.9],
    "quantity": [10, 5, 6, 8, 4],
    "city": ["Pahang", "Pahang", "Melaka", "Johor", "Pahang"]
}

In [56]:
df = pd.DataFrame(data)
df

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
2  02-01-2022   apple    1.3         6  Melaka
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [57]:
df["product"]

0     apple
1    banana
2     apple
3    orange
4    banana
Name: product, dtype: str

In [58]:
df[["product", "price"]]

  product  price
0   apple    1.2
1  banana    0.8
2   apple    1.3
3  orange    1.5
4  banana    0.9

In [59]:
df.iloc[0]

date        01-01-2022
product          apple
price              1.2
quantity            10
city            Pahang
Name: 0, dtype: object

In [60]:
df

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
2  02-01-2022   apple    1.3         6  Melaka
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [61]:
df.iloc[2]

date        02-01-2022
product          apple
price              1.3
quantity             6
city            Melaka
Name: 2, dtype: object

In [62]:
df.iloc[0:2]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang

In [63]:
df.iloc[1,2]

np.float64(0.8)

In [64]:
df

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
2  02-01-2022   apple    1.3         6  Melaka
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [65]:
df.iloc[2,0]

'02-01-2022'

In [66]:
df['product'] == 'apple'

0     True
1    False
2     True
3    False
4    False
Name: product, dtype: bool

In [67]:
mask = df['product'] == 'apple'

In [68]:
mask

0     True
1    False
2     True
3    False
4    False
Name: product, dtype: bool

In [69]:
df[mask]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
2  02-01-2022   apple    1.3         6  Melaka

In [70]:
# & - AND
# | - or
# ~ - NOT

In [71]:
# Price greater than 1.0 AND product apple
df[(df["price"] > 1.0) & (df["product"] == "apple")]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
2  02-01-2022   apple    1.3         6  Melaka

In [72]:
# Price less than 1.0 OR quantity greater than 6
df[(df["price"] < 1.0) | (df["quantity"] > 6)]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [73]:
# NOT apple
df[~(df["product"] == "apple")]

         date product  price  quantity    city
1  01-01-2022  banana    0.8         5  Pahang
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [74]:
df.loc[df["city"] == "Pahang"]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
4  03-01-2022  banana    0.9         4  Pahang

In [75]:
df.loc[0]

date        01-01-2022
product          apple
price              1.2
quantity            10
city            Pahang
Name: 0, dtype: object

In [76]:
 # df.loc[r,c]
df.loc[df["city"] == "Pahang", ["product","price"]]

  product  price
0   apple    1.2
1  banana    0.8
4  banana    0.9

In [77]:
# Multi-index
multi = df.set_index(["city", "product"])
multi

                      date  price  quantity
city   product
Pahang apple    01-01-2022    1.2        10
       banana   01-01-2022    0.8         5
Melaka apple    02-01-2022    1.3         6
Johor  orange   03-01-2022    1.5         8
Pahang banana   03-01-2022    0.9         4

In [78]:
multi.loc[("Pahang", "apple")]

C:\Users\Admin\AppData\Local\Temp\ipykernel_8100\986247814.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  multi.loc[("Pahang", "apple")]

                      date  price  quantity
city   product
Pahang apple    01-01-2022    1.2        10

In [79]:
multi

                      date  price  quantity
city   product
Pahang apple    01-01-2022    1.2        10
       banana   01-01-2022    0.8         5
Melaka apple    02-01-2022    1.3         6
Johor  orange   03-01-2022    1.5         8
Pahang banana   03-01-2022    0.9         4

In [80]:
multi.loc["Pahang"]

               date  price  quantity
product
apple    01-01-2022    1.2        10
banana   01-01-2022    0.8         5
banana   03-01-2022    0.9         4

In [81]:
df

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
2  02-01-2022   apple    1.3         6  Melaka
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [82]:
# Exercise 1 - Select the rows where quantity is greater than 5 and show date and product only

df.loc[df["quantity"] > 5, ["date", "product"]]

         date product
0  01-01-2022   apple
2  02-01-2022   apple
3  03-01-2022  orange

In [83]:
# Exercise 2 - Use iloc to select rows 1 through 3 and columns 0 through 3

df.iloc[1:4, 0:3]

         date product  price
1  01-01-2022  banana    0.8
2  02-01-2022   apple    1.3
3  03-01-2022  orange    1.5

In [84]:
# Exercise 3 - Filter rows where city is Pahang OR product is orange

df[(df["city"] == "Pahang") | (df["product"] == "orange")]

         date product  price  quantity    city
0  01-01-2022   apple    1.2        10  Pahang
1  01-01-2022  banana    0.8         5  Pahang
3  03-01-2022  orange    1.5         8   Johor
4  03-01-2022  banana    0.9         4  Pahang

In [85]:
# Exercise 4 - Create a mask for price less than 1.0 and use it to filter rows

mask = df["price"] < 1.0
df[mask]

         date product  price  quantity    city
1  01-01-2022  banana    0.8         5  Pahang
4  03-01-2022  banana    0.9         4  Pahang

In [86]:
# Exercise 5 - Convert df to a multi-index using date and city, then select all rows for 01-01-2022

mi = df.set_index(["date", "city"])
mi

                  product  price  quantity
date       city
01-01-2022 Pahang   apple    1.2        10
           Pahang  banana    0.8         5
02-01-2022 Melaka   apple    1.3         6
03-01-2022 Johor   orange    1.5         8
           Pahang  banana    0.9         4

In [87]:
mi.loc[("01-01-2022", "Pahang")]

                  product  price  quantity
date       city
01-01-2022 Pahang   apple    1.2        10
           Pahang  banana    0.8         5