In [1]:
# SERIES (single column of data)

import pandas as pd

In [3]:
ages = pd.Series([21,34,19,45])

In [4]:
ages[0]

np.int64(21)

In [5]:
ages[1:3]

1    34
2    19
dtype: int64

In [7]:
ages.max()

np.int64(45)

In [8]:
ages.min()

np.int64(19)

In [10]:
ages.mean()

np.float64(29.75)

In [12]:
ages.median()

np.float64(27.5)

In [14]:
ages.head()

0    21
1    34
2    19
3    45
dtype: int64

In [15]:
ages.tail()

0    21
1    34
2    19
3    45
dtype: int64

In [16]:
len(ages)

4

In [17]:
ages.shape

(4,)

In [18]:
ages

0    21
1    34
2    19
3    45
dtype: int64

In [21]:
# Data Frame
data = {
     "name": ["Alice", "Bob", "Charlie"],
     "age": [25, 30, 22],
     "city": ["LA", "NY", "London"]
}

In [26]:
df = pd.DataFrame(data)
df

      name  age    city
0    Alice   25      LA
1      Bob   30      NY
2  Charlie   22  London

In [27]:
type(df)

pandas.DataFrame

In [28]:
data = [
    ["Alice", 24],
    ["Bob", 30],
    ["Charlie", 19]
]

In [29]:
df = pd.DataFrame(data, columns=["name", "age"])
df

      name  age
0    Alice   24
1      Bob   30
2  Charlie   19

In [31]:
s1 = pd.Series([1,2,3], index=["a","b","c"])
s2 = pd.Series([10,20,30], index=["a","b","c"])

In [32]:
df = pd.DataFrame({"col1": s1, "col2": s2})
df

   col1  col2
a     1    10
b     2    20
c     3    30

In [33]:
df = pd.DataFrame(columns=["name", "age"])

In [36]:
df.loc[0] = ["Alice", 24]
df.loc[1] = ["Bob",30]
df

    name  age
0  Alice   24
1    Bob   30

In [39]:
data = {
     "name": ["Alice", "Bob", "Charlie"],
     "age": [25, 30, 22],
     "city": ["LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)
df

      name  age     city
0    Alice   25       LA
1      Bob   30       NY
2  Charlie   22  Chicago

In [40]:
df["name"]

0      Alice
1        Bob
2    Charlie
Name: name, dtype: str

In [41]:
df.name

0      Alice
1        Bob
2    Charlie
Name: name, dtype: str

In [42]:
df[["name", "city"]]

      name     city
0    Alice       LA
1      Bob       NY
2  Charlie  Chicago

In [43]:
df["score"] = [80,90,60]
df

      name  age     city  score
0    Alice   25       LA     80
1      Bob   30       NY     90
2  Charlie   22  Chicago     60

In [47]:
df = pd.DataFrame({
    "date": ["08-10-2023", "08-10-2024", "08-10-2025", "08-10-2026", "08-10-2027"],
    "product": ["tea", "coffee", "tea", "coffee", "tea"],
    "quantity": [4,2,3,5,10],
    "price": [40, 40, 30, 100, 10]
})
df

         date product  quantity  price
0  08-10-2023     tea         4     40
1  08-10-2024  coffee         2     40
2  08-10-2025     tea         3     30
3  08-10-2026  coffee         5    100
4  08-10-2027     tea        10     10

In [49]:
df.to_csv("sales_example.csv", index=False)

In [51]:
df.to_excel("sales_example.xlsx", index=False)

In [52]:
df.to_json("sales_example.json", orient="records", lines=False)

In [54]:
csv_df = pd.read_csv("sales_example.csv", parse_dates=["date"])
csv_df

        date product  quantity  price
0 2023-08-10     tea         4     40
1 2024-08-10  coffee         2     40
2 2025-08-10     tea         3     30
3 2026-08-10  coffee         5    100
4 2027-08-10     tea        10     10

In [56]:
excel_df = pd.read_excel("sales_example.xlsx", parse_dates=["date"])
excel_df

        date product  quantity  price
0 2023-08-10     tea         4     40
1 2024-08-10  coffee         2     40
2 2025-08-10     tea         3     30
3 2026-08-10  coffee         5    100
4 2027-08-10     tea        10     10

In [57]:
json_df = pd.read_json("sales_example.json", orient="records")
json_df

        date product  quantity  price
0 2023-08-10     tea         4     40
1 2024-08-10  coffee         2     40
2 2025-08-10     tea         3     30
3 2026-08-10  coffee         5    100
4 2027-08-10     tea        10     10

In [58]:
df

         date product  quantity  price
0  08-10-2023     tea         4     40
1  08-10-2024  coffee         2     40
2  08-10-2025     tea         3     30
3  08-10-2026  coffee         5    100
4  08-10-2027     tea        10     10

In [59]:
# Data Inspection

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      5 non-null      str
 1   product   5 non-null      str
 2   quantity  5 non-null      int64
 3   price     5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [ ]:
# 1. info() - gives a summary of the DataFrame: number of rows, column names, non-null counts and data types.
# 2. describe() - gives summary statistics for numeric columns by default: count, mean, std, min, 25%, 50%, 75%, max.
# 3. head() - shows the first rows.
# 4. tail() - shows the last rows.
# 5. dtypes - shows the type of each column.
# 6. shape - returns a tuple (rows, columns).
# 7. columns - lists the column names.

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      5 non-null      str
 1   product   5 non-null      str
 2   quantity  5 non-null      int64
 3   price     5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [61]:
df.shape

(5, 4)

In [62]:
df.columns

Index(['date', 'product', 'quantity', 'price'], dtype='str')

In [63]:
df.dtypes

date          str
product       str
quantity    int64
price       int64
dtype: object

In [64]:
df.head()

         date product  quantity  price
0  08-10-2023     tea         4     40
1  08-10-2024  coffee         2     40
2  08-10-2025     tea         3     30
3  08-10-2026  coffee         5    100
4  08-10-2027     tea        10     10

In [65]:
df.tail()

         date product  quantity  price
0  08-10-2023     tea         4     40
1  08-10-2024  coffee         2     40
2  08-10-2025     tea         3     30
3  08-10-2026  coffee         5    100
4  08-10-2027     tea        10     10

In [66]:
df.describe()

        quantity       price
count   5.000000    5.000000
mean    4.800000   44.000000
std     3.114482   33.615473
min     2.000000   10.000000
25%     3.000000   30.000000
50%     4.000000   40.000000
75%     5.000000   40.000000
max    10.000000  100.000000

In [67]:
df.describe(include="all")

              date product   quantity       price
count            5       5   5.000000    5.000000
unique           5       2        NaN         NaN
top     08-10-2023     tea        NaN         NaN
freq             1       3        NaN         NaN
mean           NaN     NaN   4.800000   44.000000
std            NaN     NaN   3.114482   33.615473
min            NaN     NaN   2.000000   10.000000
25%            NaN     NaN   3.000000   30.000000
50%            NaN     NaN   4.000000   40.000000
75%            NaN     NaN   5.000000   40.000000
max            NaN     NaN  10.000000  100.000000

In [70]:
df.describe(include='string').transpose()

        count unique         top freq
date        5      5  08-10-2023    1
product     5      2         tea    3

In [71]:
df

         date product  quantity  price
0  08-10-2023     tea         4     40
1  08-10-2024  coffee         2     40
2  08-10-2025     tea         3     30
3  08-10-2026  coffee         5    100
4  08-10-2027     tea        10     10

In [74]:
df["product"].nunique()

2