In [2]:
# Nan or None

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Name": ["Fatin", "Nabila", "Farah", "Hannani"],
    "Age": [25, None, 30, np.nan],
    "City": ["NY", "LA", None, "Chicago"]
}

In [42]:
df = pd.DataFrame(data)
df

      Name   Age     City
0    Fatin  25.0       NY
1   Nabila   NaN       LA
2    Farah  30.0      NaN
3  Hannani   NaN  Chicago

In [6]:
df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(3)

In [8]:
df_filled = df.fillna({"Age": df['Age'].mean(), "City": 'Unknown'})

In [9]:
df_filled

      Name   Age     City
0    Fatin  25.0       NY
1   Nabila  27.5       LA
2    Farah  30.0  Unknown
3  Hannani  27.5  Chicago

In [10]:
df_filled.isnull().sum().sum()

np.int64(0)

In [11]:
df

      Name   Age     City
0    Fatin  25.0       NY
1   Nabila   NaN       LA
2    Farah  30.0      NaN
3  Hannani   NaN  Chicago

In [12]:
df_dropped = df.dropna()

In [13]:
df_dropped

    Name   Age City
0  Fatin  25.0   NY

In [14]:
df.dtypes

Name        str
Age     float64
City        str
dtype: object

In [15]:
df_filled

      Name   Age     City
0    Fatin  25.0       NY
1   Nabila  27.5       LA
2    Farah  30.0  Unknown
3  Hannani  27.5  Chicago

In [16]:
df_filled["Age"] = df_filled["Age"].astype("int")

In [17]:
df_filled["Age"]

0    25
1    27
2    30
3    27
Name: Age, dtype: int64

In [18]:
df

      Name   Age     City
0    Fatin  25.0       NY
1   Nabila   NaN       LA
2    Farah  30.0      NaN
3  Hannani   NaN  Chicago

In [19]:
# ada dua cara
# 1. letak inplace=True
# 2. assigned to new value

In [22]:
df_rename = df.rename(columns={"Name": "CustomerName", "Age": "CustomerAge"})

In [23]:
df_rename

  CustomerName  CustomerAge     City
0        Fatin         25.0       NY
1       Nabila          NaN       LA
2        Farah         30.0      NaN
3      Hannani          NaN  Chicago

In [26]:
df.duplicated().sum()

np.int64(0)

In [28]:
df3 = pd.DataFrame({"X": [1,1,2,3], "Y": ["a","a","b","c"]})
df3

   X  Y
0  1  a
1  1  a
2  2  b
3  3  c

In [31]:
df3.duplicated().sum()

np.int64(1)

In [33]:
df3_clean = df3.drop_duplicates()
df3_clean

   X  Y
0  1  a
2  2  b
3  3  c

In [34]:
df

  CustomerName  CustomerAge     City
0        Fatin         25.0       NY
1       Nabila          NaN       LA
2        Farah         30.0      NaN
3      Hannani          NaN  Chicago

In [35]:
df_city_fixed = df.replace({"City": {"NY": "New York", "LA": "Los Angeles"}})

In [46]:
df_city_fixed

  CustomerName  CustomerAge         City
0        Fatin         25.0     New York
1       Nabila          NaN  Los Angeles
2        Farah         30.0          NaN
3      Hannani          NaN      Chicago

In [37]:
rating_map = {"A": 5, "B": 4, "C": 3}

In [38]:
df5 = pd.DataFrame({"Grade": ["A","B","A","C"]})

In [48]:
df5

  Grade
0     A
1     B
2     A
3     C

In [49]:
df5["Score"] = df5["Grade"].map(rating_map)
df5

  Grade  Score
0     A      5
1     B      4
2     A      5
3     C      3

In [50]:
def add_exclamation(x):
    return x + "!"

In [51]:
df6 = pd.DataFrame({"Word": ["hi", "hello"]})
df6

    Word
0     hi
1  hello

In [52]:
df6["Shout"] = df6["Word"].apply(add_exclamation)
df6

    Word   Shout
0     hi     hi!
1  hello  hello!