In [1]:
# Parse messy date strings into clean timestamps
# Group data by year, month, week or hour
# Fill missing datesCompute moving averages
# Shift data forward or backward in time
# Create forecasts or trends

In [2]:
"2024-05-21" or "05/21024 15:30"

'2024-05-21'

In [3]:
type("2024-05-21")

str

In [4]:
import pandas as pd
type(pd.to_datetime("2024-05-21"))

pandas.Timestamp

In [5]:
data = {
    "date": ["2024-01-01", "2024-01-02","2024/01/03", 'Jan 4 2024'],
    "sales": [100,120,90,160]
}

In [6]:
df = pd.DataFrame(data)
df

         date  sales
0  2024-01-01    100
1  2024-01-02    120
2  2024/01/03     90
3  Jan 4 2024    160

In [7]:
df.dtypes

date       str
sales    int64
dtype: object

In [8]:
df["date"] = pd.to_datetime(df["date"], format="mixed")

In [9]:
df

        date  sales
0 2024-01-01    100
1 2024-01-02    120
2 2024-01-03     90
3 2024-01-04    160

In [10]:
df.dtypes

date     datetime64[us]
sales             int64
dtype: object

In [11]:
rng = pd.date_range(start="2024-01-01", periods=7, freq="D")
rng

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07'],
              dtype='datetime64[us]', freq='D')

In [12]:
df = pd.DataFrame({"sales": [10,20,15,30,40,35,50]}, index=rng)
df

            sales
2024-01-01     10
2024-01-02     20
2024-01-03     15
2024-01-04     30
2024-01-05     40
2024-01-06     35
2024-01-07     50

In [13]:
df.resample("W").sum()

            sales
2024-01-07    200

In [14]:
df.resample("2D").mean()

            sales
2024-01-01   15.0
2024-01-03   22.5
2024-01-05   37.5
2024-01-07   50.0

In [15]:
df

            sales
2024-01-01     10
2024-01-02     20
2024-01-03     15
2024-01-04     30
2024-01-05     40
2024-01-06     35
2024-01-07     50

In [16]:
df["rollind_3day"] = df["sales"].rolling(3).mean()

In [17]:
df

            sales  rollind_3day
2024-01-01     10           NaN
2024-01-02     20           NaN
2024-01-03     15     15.000000
2024-01-04     30     21.666667
2024-01-05     40     28.333333
2024-01-06     35     35.000000
2024-01-07     50     41.666667

In [18]:
df["roll_sum_2day"] = df["sales"].rolling(2).sum()

In [19]:
df

            sales  rollind_3day  roll_sum_2day
2024-01-01     10           NaN            NaN
2024-01-02     20           NaN           30.0
2024-01-03     15     15.000000           35.0
2024-01-04     30     21.666667           45.0
2024-01-05     40     28.333333           70.0
2024-01-06     35     35.000000           75.0
2024-01-07     50     41.666667           85.0

In [20]:
df

            sales  rollind_3day  roll_sum_2day
2024-01-01     10           NaN            NaN
2024-01-02     20           NaN           30.0
2024-01-03     15     15.000000           35.0
2024-01-04     30     21.666667           45.0
2024-01-05     40     28.333333           70.0
2024-01-06     35     35.000000           75.0
2024-01-07     50     41.666667           85.0

In [21]:
df["yesterday_sales"] = df["sales"].shift(1)
df

            sales  rollind_3day  roll_sum_2day  yesterday_sales
2024-01-01     10           NaN            NaN              NaN
2024-01-02     20           NaN           30.0             10.0
2024-01-03     15     15.000000           35.0             20.0
2024-01-04     30     21.666667           45.0             15.0
2024-01-05     40     28.333333           70.0             30.0
2024-01-06     35     35.000000           75.0             40.0
2024-01-07     50     41.666667           85.0             35.0

In [22]:
df["change"] = df["sales"] - df["yesterday_sales"]
df

            sales  rollind_3day  roll_sum_2day  yesterday_sales  change
2024-01-01     10           NaN            NaN              NaN     NaN
2024-01-02     20           NaN           30.0             10.0    10.0
2024-01-03     15     15.000000           35.0             20.0    -5.0
2024-01-04     30     21.666667           45.0             15.0    15.0
2024-01-05     40     28.333333           70.0             30.0    10.0
2024-01-06     35     35.000000           75.0             40.0    -5.0
2024-01-07     50     41.666667           85.0             35.0    15.0

In [23]:
df["shift_2"] = df["sales"].shift(2)
df

,sales,rollind_3day,roll_sum_2day,yesterday_sales,change,shift_2
2024-01-01,10,NaN,NaN,NaN,NaN,NaN
2024-01-02,20,NaN,30.0,10.0,10.0,NaN
2024-01-03,15,15.000000,35.0,20.0,-5.0,10.0
2024-01-04,30,21.666667,45.0,15.0,15.0,20.0
2024-01-05,40,28.333333,70.0,30.0,10.0,15.0
2024-01-06,35,35.000000,75.0,40.0,-5.0,30.0
2024-01-07,50,41.666667,85.0,35.0,15.0,40.0

In [24]:
df = df["sales"]

In [25]:
df.index.day_name()

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday'],
      dtype='str')

In [26]:
df["month"] = df.index.month

In [27]:
df

2024-01-01 00:00:00                                             10
2024-01-02 00:00:00                                             20
2024-01-03 00:00:00                                             15
2024-01-04 00:00:00                                             30
2024-01-05 00:00:00                                             40
2024-01-06 00:00:00                                             35
2024-01-07 00:00:00                                             50
month                  Index([1, 1, 1, 1, 1, 1, 1], dtype='int32')
Name: sales, dtype: object

In [30]:
df = df.drop("month")

# Convert Series to DataFrame
df = df.to_frame(name="sales")

# Ensure the index is datetime
df.index = pd.to_datetime(df.index)

# Add month and weekday columns
df["month"] = df.index.month
df["weekday"] = df.index.day_name()

df

           sales  month    weekday
2024-01-01    10      1     Monday
2024-01-02    20      1    Tuesday
2024-01-03    15      1  Wednesday
2024-01-04    30      1   Thursday
2024-01-05    40      1     Friday
2024-01-06    35      1   Saturday
2024-01-07    50      1     Sunday

In [31]:
df.loc["2024-01-03": "2024-01-06"]

           sales  month    weekday
2024-01-03    15      1  Wednesday
2024-01-04    30      1   Thursday
2024-01-05    40      1     Friday
2024-01-06    35      1   Saturday

In [32]:
df.groupby(df.index.day_name())["sales"].sum()

Friday       40
Monday       10
Saturday     35
Sunday       50
Thursday     30
Tuesday      20
Wednesday    15
Name: sales, dtype: object